## github work flow
name: Deploy Node.js App

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    name: Unit testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Login to DockerHub
        run: |
          echo echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin