## github work flow
name: Deploy Node.js App

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    name: Unit testing
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      -
        name: Terraform SetUp
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      
      -
        name: Terraform Init
        id: init
        run: terraform init

      -
        name: Terraform Format
        id: fmt
        run: terraform fmt -check

      -
        name: Terraform Validate
        id: validate
        run: terraform validate

      -
        name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: false

      -
        name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

      -
        name: Get Nodes
        run: kubectl get nodes

      - name: Debug
        run: echo "Building as ${{ vars.DOCKERHUB_USERNAME }}"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}