## github work flow
name: Deploy Node.js App

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    name: Unit testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      -
        name: Terraform SetUp
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      
      -
        name: Terraform Init
        id: init
        run: terraform init

      - name: Debug
        run: echo "Building as ${{ vars.DOCKERHUB_USERNAME }}"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}